services:
  database:
    image: postgres
    container_name: database 
    restart: always
    env_file: .env.development
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 10s
      retries: 10 

  mailhog:
    image: mailhog/mailhog
    container_name: mainhog
    logging:
      driver: 'none'  
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  backend:
    container_name: backend
    build:
      dockerfile: docker/backend/Dockerfile 
      context: ../../

    ports:
      - "3001:3001"

    env_file: .env.development
    depends_on:
      database:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "node", "-e", "fetch('http://localhost:3001/health').then(r => { if (!r.ok) process.exit(1) }).catch(() => process.exit(1))" ]
      interval: 1s
      timeout: 10s
      retries: 10 

  web:
    container_name: web 
    build:
      dockerfile: docker/web/Dockerfile 
      context: ../../
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
    env_file: .env.development
    depends_on:
      backend:
        condition: service_healthy
