import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client.js";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const NAMES: Record<string, string> = {
  "0G": "0G",
  "2Z": "2Z",
  AAVE: "Aave",
  ADA: "Cardano",
  AERO: "Aerodrome",
  APE: "ApeCoin",
  APT: "Aptos",
  ARB: "Arbitrum",
  ASTER: "Aster",
  AVAX: "Avalanche",
  AVNT: "Avantis",
  BERA: "Berachain",
  BLUE: "Blue",
  BNB: "BNB",
  BONK: "Bonk",
  BP: "BP",
  BTC: "Bitcoin",
  CC: "CC",
  CLOUD: "Cloud",
  CRV: "Curve",
  DEEP: "Deep",
  DOGE: "Dogecoin",
  DOT: "Polkadot",
  EDGE: "Edge",
  ENA: "Ethena",
  ES: "ES",
  ETH: "Ethereum",
  FARTCOIN: "Fartcoin",
  FLOCK: "Flock",
  FOGO: "Fogo",
  HBAR: "Hedera",
  HYPE: "Hyperliquid",
  IO: "io.net",
  IP: "IP",
  JTO: "Jito",
  JUP: "Jupiter",
  KAITO: "Kaito",
  KMNO: "Kamino",
  kBONK: "kBonk",
  kPEPE: "kPepe",
  kSHIB: "kShiba",
  LDO: "Lido",
  LINEA: "Linea",
  LINK: "Chainlink",
  LIT: "Lit Protocol",
  LTC: "Litecoin",
  MEGA: "Mega",
  MET: "Met",
  MNT: "Mantle",
  MON: "Monad",
  NEAR: "NEAR",
  ONDO: "Ondo",
  OP: "Optimism",
  PAXG: "PAX Gold",
  PENDLE: "Pendle",
  PENGU: "Pengu",
  PEPE: "Pepe",
  PIPE: "Pipe",
  POL: "Polygon",
  PUMP: "Pump",
  PYTH: "Pyth",
  RAY: "Raydium",
  RENDER: "Render",
  S: "Sonic",
  SEI: "Sei",
  SHIB: "Shiba Inu",
  SKR: "SKR",
  SOL: "Solana",
  STABLE: "Stable",
  STRK: "Starknet",
  SUI: "Sui",
  TAO: "Bittensor",
  TIA: "Celestia",
  TON: "Toncoin",
  TRUMP: "Trump",
  UNI: "Uniswap",
  USDT: "Tether",
  VIRTUAL: "Virtual",
  W: "Wormhole",
  WAL: "Walrus",
  WIF: "dogwifhat",
  WLFI: "World Liberty Fi",
  WLD: "Worldcoin",
  XLM: "Stellar",
  XMR: "Monero",
  XPL: "XPL",
  XRP: "XRP",
  ZAMA: "Zama",
  ZEC: "Zcash",
  ZORA: "Zora",
  ZRO: "LayerZero",
};

const RAW_SYMBOLS = [
  "0G_USDC",
  "0G_USDC_PERP",
  "2Z_USDC",
  "2Z_USDC_PERP",
  "AAVE_USDC",
  "AAVE_USDC_PERP",
  "ADA_USDC_PERP",
  "AERO_USDC_PERP",
  "APE_USDC",
  "APT_USDC",
  "APT_USDC_PERP",
  "ARB_USDC_PERP",
  "ASTER_USDC_PERP",
  "AVAX_USDC_PERP",
  "AVNT_USDC_PERP",
  "BERA_USDC_PERP",
  "BLUE_USDC",
  "BNB_USDC",
  "BNB_USDC_PERP",
  "BONK_USDC",
  "BP_USDC",
  "BTC_USDC",
  "BTC_USDC_PERP",
  "CC_USDC_PERP",
  "CLOUD_USDC",
  "CRV_USDC_PERP",
  "DEEP_USDC",
  "DOGE_USDC",
  "DOGE_USDC_PERP",
  "DOT_USDC_PERP",
  "EDGE_USDC_PERP",
  "ENA_USDC",
  "ENA_USDC_PERP",
  "ES_USDC",
  "ETH_USDC",
  "ETH_USDC_PERP",
  "FARTCOIN_USDC_PERP",
  "FLOCK_USDC",
  "FLOCK_USDC_PERP",
  "FOGO_USDC",
  "FOGO_USDC_PERP",
  "HBAR_USDC_PERP",
  "HYPE_USDC",
  "HYPE_USDC_PERP",
  "IO_USDC",
  "IP_USDC_PERP",
  "JTO_USDC",
  "JTO_USDC_PERP",
  "JUP_USDC",
  "JUP_USDC_PERP",
  "KAITO_USDC_PERP",
  "KMNO_USDC_PERP",
  "KMNO_USDC",
  "LDO_USDC",
  "LDO_USDC_PERP",
  "LINEA_USDC_PERP",
  "LINK_USDC",
  "LINK_USDC_PERP",
  "LIT_USDC_PERP",
  "LTC_USDC_PERP",
  "MEGA_USDC_PERP",
  "MET_USDC",
  "MET_USDC_PERP",
  "MNT_USDC_PERP",
  "MON_USDC",
  "MON_USDC_PERP",
  "NEAR_USDC_PERP",
  "ONDO_USDC",
  "ONDO_USDC_PERP",
  "OP_USDC_PERP",
  "PAXG_USDC",
  "PAXG_USDC_PERP",
  "PENDLE_USDC_PERP",
  "PENGU_USDC",
  "PENGU_USDC_PERP",
  "PEPE_USDC",
  "PIPE_USDC",
  "POL_USDC",
  "PUMP_USDC",
  "PUMP_USDC_PERP",
  "PYTH_USDC",
  "PYTH_USDC_PERP",
  "RAY_USDC",
  "RENDER_USDC",
  "S_USDC_PERP",
  "SEI_USDC",
  "SEI_USDC_PERP",
  "SHIB_USDC",
  "SKR_USDC",
  "SKR_USDC_PERP",
  "SOL_USDC",
  "SOL_USDC_PERP",
  "STABLE_USDC",
  "STABLE_USDC_PERP",
  "STRK_USDC",
  "STRK_USDC_PERP",
  "SUI_USDC",
  "SUI_USDC_PERP",
  "TAO_USDC_PERP",
  "TIA_USDC_PERP",
  "TON_USDC_PERP",
  "TRUMP_USDC",
  "TRUMP_USDC_PERP",
  "UNI_USDC",
  "UNI_USDC_PERP",
  "USDT_USDC",
  "VIRTUAL_USDC_PERP",
  "W_USDC",
  "W_USDC_PERP",
  "WAL_USDC",
  "WIF_USDC",
  "WIF_USDC_PERP",
  "WLD_USDC",
  "WLD_USDC_PERP",
  "WLFI_USDC",
  "WLFI_USDC_PERP",
  "XLM_USDC_PERP",
  "XMR_USDC_PERP",
  "XPL_USDC",
  "XPL_USDC_PERP",
  "XRP_USDC",
  "XRP_USDC_PERP",
  "ZAMA_USDC_PERP",
  "ZEC_USDC",
  "ZEC_USDC_PERP",
  "ZORA_USDC_PERP",
  "ZRO_USDC",
  "ZRO_USDC_PERP",
  "kBONK_USDC_PERP",
  "kPEPE_USDC_PERP",
  "kSHIB_USDC_PERP",
];

function parseSymbol(symbol: string): {
  baseCurrency: string;
  quoteCurrency: string;
  category: "SPOT" | "FUTURES";
} {
  const isPerp = symbol.endsWith("_PERP");
  const base = isPerp
    ? symbol.slice(0, -"_USDC_PERP".length)
    : symbol.slice(0, -"_USDC".length);
  return {
    baseCurrency: base,
    quoteCurrency: "USDC",
    category: isPerp ? "FUTURES" : "SPOT",
  };
}

async function main() {
  const markets = RAW_SYMBOLS.map((symbol) => {
    const { baseCurrency, quoteCurrency, category } = parseSymbol(symbol);
    return {
      symbol,
      baseCurrency,
      quoteCurrency,
      name: NAMES[baseCurrency] ?? baseCurrency,
      category: category as "SPOT" | "FUTURES",
      tags: [] as string[],
      minOrderSize: 0.001,
      tickSize: 0.01,
      isActive: true,
    };
  });

  await prisma.market.createMany({ data: markets, skipDuplicates: true });
  console.log(`Seeded ${markets.length} markets`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
